---
apiVersion: v1
kind: Namespace
metadata:
  name: development
  labels:
    name: development

# kubectl create -f namespace-dev.yaml
# kubectl get svc -n development
# kubectl config set-context dev --namespace=development --cluster=lithe-cocoa-92103_kubernetes --user=lithe-cocoa-92103_kubernetes
# kubectl config set-context prod --namespace=production --cluster=lithe-cocoa-92103_kubernetes --user=lithe-cocoa-92103_kubernetes
# kubectl config view
