apiVersion: apps/v1
kind: ReplicaSet
metadata:
  creationTimestamp: "2025-11-20T04:06:20Z"
  generation: 1
  name: new-replica-set
  namespace: default
  resourceVersion: "1236"
  uid: 4f38ba2f-272d-4549-a3b6-c08f7c821ec8
spec:
  replicas: 5
  selector:
    matchLabels:
      name: busybox-pod
  template:
    metadata:
      labels:
        name: busybox-pod
    spec:
      containers:
      - command:
        - sh
        - -c
        - echo Hello Kubernetes! && sleep 3600
        image: busybox
        imagePullPolicy: Always
        name: busybox-container
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  fullyLabeledReplicas: 5
  observedGeneration: 1
  replicas: 5
