apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end
spec:
  template:
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
          name: http
