apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  selector:
    name: simple-webapp
  ports:
    - port: 8080        # Service port
      targetPort: 8080  # Container port
      nodePort: 30080   # NodePort (external access)

